#!/bin/sh

rm -r process*
rm -r postProcess*
rm -r log.*

rm -r 0.* [1-9]*
rm -r VTK

# in case max memory is exceeded
rm core.*
rm slurm*
#------------------------------------------------------------------------------
